import "@/styles/globals.css";

export const metadata = {
  title: "QR Code Component",
  description: "Generated by Next.js",
  icons: "/qrcode-component/assets/images/favicon-32x32.png"
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-slate-300">{children}</body>
    </html>
  );
}
